graph TD
    Phonebook.RyanW84[Phonebook.RyanW84]
    Phonebook.RyanW84-->Phonebook.RyanW84API[API]
    Phonebook.RyanW84API-->Phonebook.RyanW84APIEmailPerson.cs((EmailPerson.cs))
    Phonebook.RyanW84APIEmailPerson.cs-->|class|Phonebook.RyanW84APIEmailPerson.csEmailPerson[EmailPerson]
    Phonebook.RyanW84APIEmailPerson.csEmailPerson-->|method|Phonebook.RyanW84APIEmailPerson.csEmailPersonEmail(Email)
    Phonebook.RyanW84API-->Phonebook.RyanW84APIReadSecrets.cs((ReadSecrets.cs))
    Phonebook.RyanW84APIReadSecrets.cs-->|class|Phonebook.RyanW84APIReadSecrets.csSecretAppsettingReader[SecretAppsettingReader]
    Phonebook.RyanW84APIReadSecrets.csSecretAppsettingReader-->|method|Phonebook.RyanW84APIReadSecrets.csSecretAppsettingReaderReadSection(ReadSection)
    Phonebook.RyanW84API-->Phonebook.RyanW84APITextPerson.cs((TextPerson.cs))
    Phonebook.RyanW84APITextPerson.cs-->|class|Phonebook.RyanW84APITextPerson.csTextPerson[TextPerson]
    Phonebook.RyanW84APITextPerson.csTextPerson-->|method|Phonebook.RyanW84APITextPerson.csTextPersonText(Text)
    Phonebook.RyanW84-->Phonebook.RyanW84Controllers[Controllers]
    Phonebook.RyanW84Controllers-->Phonebook.RyanW84ControllersCategoryController.cs((CategoryController.cs))
    Phonebook.RyanW84ControllersCategoryController.cs-->|class|Phonebook.RyanW84ControllersCategoryController.csCategoryController[CategoryController]
    Phonebook.RyanW84ControllersCategoryController.csCategoryController-->|method|Phonebook.RyanW84ControllersCategoryController.csCategoryControllerAddCategory(AddCategory)
    Phonebook.RyanW84ControllersCategoryController.csCategoryController-->|method|Phonebook.RyanW84ControllersCategoryController.csCategoryControllerDeleteCategory(DeleteCategory)
    Phonebook.RyanW84ControllersCategoryController.csCategoryController-->|method|Phonebook.RyanW84ControllersCategoryController.csCategoryControllerUpdateCategory(UpdateCategory)
    Phonebook.RyanW84ControllersCategoryController.csCategoryController-->|method|Phonebook.RyanW84ControllersCategoryController.csCategoryControllerGetCategories(GetCategories)
    Phonebook.RyanW84Controllers-->Phonebook.RyanW84ControllersPersonController.cs((PersonController.cs))
    Phonebook.RyanW84ControllersPersonController.cs-->|class|Phonebook.RyanW84ControllersPersonController.csPersonController[PersonController]
    Phonebook.RyanW84ControllersPersonController.csPersonController-->|method|Phonebook.RyanW84ControllersPersonController.csPersonControllerAddPerson(AddPerson)
    Phonebook.RyanW84ControllersPersonController.csPersonController-->|method|Phonebook.RyanW84ControllersPersonController.csPersonControllerDeletePerson(DeletePerson)
    Phonebook.RyanW84ControllersPersonController.csPersonController-->|method|Phonebook.RyanW84ControllersPersonController.csPersonControllerUpdatePerson(UpdatePerson)
    Phonebook.RyanW84ControllersPersonController.csPersonController-->|method|Phonebook.RyanW84ControllersPersonController.csPersonControllerGetContactById(GetContactById)
    Phonebook.RyanW84ControllersPersonController.csPersonController-->|method|Phonebook.RyanW84ControllersPersonController.csPersonControllerGetPersons(GetPersons)
    Phonebook.RyanW84-->Phonebook.RyanW84DataConnection[DataConnection]
    Phonebook.RyanW84DataConnection-->Phonebook.RyanW84DataConnectionConnectionChecker.cs((ConnectionChecker.cs))
    Phonebook.RyanW84DataConnectionConnectionChecker.cs-->|class|Phonebook.RyanW84DataConnectionConnectionChecker.csConnectionChecker[ConnectionChecker]
    Phonebook.RyanW84DataConnectionConnectionChecker.csConnectionChecker-->|method|Phonebook.RyanW84DataConnectionConnectionChecker.csConnectionCheckerTestDatabaseConnection(TestDatabaseConnection)
    Phonebook.RyanW84DataConnection-->Phonebook.RyanW84DataConnectionPhonebookDBContext.cs((PhonebookDBContext.cs))
    Phonebook.RyanW84DataConnectionPhonebookDBContext.cs-->|class|Phonebook.RyanW84DataConnectionPhonebookDBContext.csPhonebookDBContext[PhonebookDBContext]
    Phonebook.RyanW84DataConnectionPhonebookDBContext.csPhonebookDBContext-->|method|Phonebook.RyanW84DataConnectionPhonebookDBContext.csPhonebookDBContextOnConfiguring(OnConfiguring)
    Phonebook.RyanW84DataConnectionPhonebookDBContext.csPhonebookDBContext-->|method|Phonebook.RyanW84DataConnectionPhonebookDBContext.csPhonebookDBContextGetLoggerFactory(GetLoggerFactory)
    Phonebook.RyanW84DataConnectionPhonebookDBContext.csPhonebookDBContext-->|method|Phonebook.RyanW84DataConnectionPhonebookDBContext.csPhonebookDBContextOnModelCreating(OnModelCreating)
    Phonebook.RyanW84-->Phonebook.RyanW84Diagrams[Diagrams]
    Phonebook.RyanW84Diagrams-->Phonebook.RyanW84DiagramsER_Diagram.png((ER Diagram.png))
    Phonebook.RyanW84-->Phonebook.RyanW84Menu[Menu]
    Phonebook.RyanW84Menu-->Phonebook.RyanW84MenuEnums.cs((Enums.cs))
    Phonebook.RyanW84MenuEnums.cs-->|class|Phonebook.RyanW84MenuEnums.csEnums[Enums]
    Phonebook.RyanW84Menu-->Phonebook.RyanW84MenuUserInterface.cs((UserInterface.cs))
    Phonebook.RyanW84MenuUserInterface.cs-->|class|Phonebook.RyanW84MenuUserInterface.csUserInterface[UserInterface]
    Phonebook.RyanW84MenuUserInterface.csUserInterface-->|method|Phonebook.RyanW84MenuUserInterface.csUserInterfaceGetEnumDisplayName(GetEnumDisplayName)
    Phonebook.RyanW84MenuUserInterface.csUserInterface-->|method|Phonebook.RyanW84MenuUserInterface.csUserInterfaceMainMenu(MainMenu)
    Phonebook.RyanW84MenuUserInterface.csUserInterface-->|method|Phonebook.RyanW84MenuUserInterface.csUserInterfacePersonMenu(PersonMenu)
    Phonebook.RyanW84MenuUserInterface.csUserInterface-->|method|Phonebook.RyanW84MenuUserInterface.csUserInterfaceCategoriesMenu(CategoriesMenu)
    Phonebook.RyanW84MenuUserInterface.csUserInterface-->|method|Phonebook.RyanW84MenuUserInterface.csUserInterfaceContactMenu(ContactMenu)
    Phonebook.RyanW84MenuUserInterface.csUserInterface-->|method|Phonebook.RyanW84MenuUserInterface.csUserInterfaceShowPerson(ShowPerson)
    Phonebook.RyanW84MenuUserInterface.csUserInterface-->|method|Phonebook.RyanW84MenuUserInterface.csUserInterfaceShowPersonsTable(ShowPersonsTable)
    Phonebook.RyanW84MenuUserInterface.csUserInterface-->|method|Phonebook.RyanW84MenuUserInterface.csUserInterfaceShowCategoryTable(ShowCategoryTable)
    Phonebook.RyanW84MenuUserInterface.csUserInterface-->|method|Phonebook.RyanW84MenuUserInterface.csUserInterfaceShowCategory(ShowCategory)
    Phonebook.RyanW84-->Phonebook.RyanW84Migrations[Migrations]
    Phonebook.RyanW84Migrations-->Phonebook.RyanW84Migrations20250412193218_InitialCreation.cs((20250412193218_InitialCreation.cs))
    Phonebook.RyanW84Migrations20250412193218_InitialCreation.cs-->|class|Phonebook.RyanW84Migrations20250412193218_InitialCreation.csInitialCreation[InitialCreation]
    Phonebook.RyanW84Migrations20250412193218_InitialCreation.csInitialCreation-->|method|Phonebook.RyanW84Migrations20250412193218_InitialCreation.csInitialCreationUp(Up)
    Phonebook.RyanW84Migrations20250412193218_InitialCreation.csInitialCreation-->|method|Phonebook.RyanW84Migrations20250412193218_InitialCreation.csInitialCreationDown(Down)
    Phonebook.RyanW84Migrations-->Phonebook.RyanW84Migrations20250412193218_InitialCreation.Designer.cs((20250412193218_InitialCreation.Designer.cs))
    Phonebook.RyanW84Migrations20250412193218_InitialCreation.Designer.cs-->|class|Phonebook.RyanW84Migrations20250412193218_InitialCreation.Designer.csInitialCreation[InitialCreation]
    Phonebook.RyanW84Migrations20250412193218_InitialCreation.Designer.csInitialCreation-->|method|Phonebook.RyanW84Migrations20250412193218_InitialCreation.Designer.csInitialCreationBuildTargetModel(BuildTargetModel)
    Phonebook.RyanW84Migrations-->Phonebook.RyanW84MigrationsPhonebookDBContextModelSnapshot.cs((PhonebookDBContextModelSnapshot.cs))
    Phonebook.RyanW84MigrationsPhonebookDBContextModelSnapshot.cs-->|class|Phonebook.RyanW84MigrationsPhonebookDBContextModelSnapshot.csPhonebookDBContextModelSnapshot[PhonebookDBContextModelSnapshot]
    Phonebook.RyanW84MigrationsPhonebookDBContextModelSnapshot.csPhonebookDBContextModelSnapshot-->|method|Phonebook.RyanW84MigrationsPhonebookDBContextModelSnapshot.csPhonebookDBContextModelSnapshotBuildModel(BuildModel)
    Phonebook.RyanW84-->Phonebook.RyanW84Models[Models]
    Phonebook.RyanW84Models-->Phonebook.RyanW84ModelsCategory.cs((Category.cs))
    Phonebook.RyanW84ModelsCategory.cs-->|class|Phonebook.RyanW84ModelsCategory.csCategory[Category]
    Phonebook.RyanW84Models-->Phonebook.RyanW84ModelsPerson.cs((Person.cs))
    Phonebook.RyanW84ModelsPerson.cs-->|class|Phonebook.RyanW84ModelsPerson.csPerson[Person]
    Phonebook.RyanW84-->Phonebook.RyanW84Services[Services]
    Phonebook.RyanW84Services-->Phonebook.RyanW84ServicesCategoryService.cs((CategoryService.cs))
    Phonebook.RyanW84ServicesCategoryService.cs-->|class|Phonebook.RyanW84ServicesCategoryService.csCategoryService[CategoryService]
    Phonebook.RyanW84ServicesCategoryService.csCategoryService-->|method|Phonebook.RyanW84ServicesCategoryService.csCategoryServiceInsertCategory(InsertCategory)
    Phonebook.RyanW84ServicesCategoryService.csCategoryService-->|method|Phonebook.RyanW84ServicesCategoryService.csCategoryServiceDeleteCategory(DeleteCategory)
    Phonebook.RyanW84ServicesCategoryService.csCategoryService-->|method|Phonebook.RyanW84ServicesCategoryService.csCategoryServiceUpdateCategory(UpdateCategory)
    Phonebook.RyanW84ServicesCategoryService.csCategoryService-->|method|Phonebook.RyanW84ServicesCategoryService.csCategoryServiceGetCategoryOptionInput(GetCategoryOptionInput)
    Phonebook.RyanW84ServicesCategoryService.csCategoryService-->|method|Phonebook.RyanW84ServicesCategoryService.csCategoryServiceGetCategory(GetCategory)
    Phonebook.RyanW84ServicesCategoryService.csCategoryService-->|method|Phonebook.RyanW84ServicesCategoryService.csCategoryServiceGetCategories(GetCategories)
    Phonebook.RyanW84Services-->Phonebook.RyanW84ServicesPersonService.cs((PersonService.cs))
    Phonebook.RyanW84ServicesPersonService.cs-->|class|Phonebook.RyanW84ServicesPersonService.csPersonService[PersonService]
    Phonebook.RyanW84ServicesPersonService.csPersonService-->|method|Phonebook.RyanW84ServicesPersonService.csPersonServiceInsertPerson(InsertPerson)
    Phonebook.RyanW84ServicesPersonService.csPersonService-->|method|Phonebook.RyanW84ServicesPersonService.csPersonServiceDeletePerson(DeletePerson)
    Phonebook.RyanW84ServicesPersonService.csPersonService-->|method|Phonebook.RyanW84ServicesPersonService.csPersonServiceUpdatePerson(UpdatePerson)
    Phonebook.RyanW84ServicesPersonService.csPersonService-->|method|Phonebook.RyanW84ServicesPersonService.csPersonServiceEmailPerson(EmailPerson)
    Phonebook.RyanW84ServicesPersonService.csPersonService-->|method|Phonebook.RyanW84ServicesPersonService.csPersonServiceGetPerson(GetPerson)
    Phonebook.RyanW84ServicesPersonService.csPersonService-->|method|Phonebook.RyanW84ServicesPersonService.csPersonServiceGetPersons(GetPersons)
    Phonebook.RyanW84ServicesPersonService.csPersonService-->|method|Phonebook.RyanW84ServicesPersonService.csPersonServiceGetPersonOptionInput(GetPersonOptionInput)
    Phonebook.RyanW84-->Phonebook.RyanW84TestResults[TestResults]
    Phonebook.RyanW84TestResults-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195241_9648[Deploy_Ryanw 20250413T195241_9648]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195241_9648-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195241_9648In[In]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195241_9648In-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195241_9648InFAWKES[FAWKES]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195241_9648-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195241_9648Out[Out]
    Phonebook.RyanW84TestResults-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195254_9440[Deploy_Ryanw 20250413T195254_9440]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195254_9440-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195254_9440In[In]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195254_9440In-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195254_9440InFAWKES[FAWKES]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195254_9440-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195254_9440Out[Out]
    Phonebook.RyanW84TestResults-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195300_17816[Deploy_Ryanw 20250413T195300_17816]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195300_17816-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195300_17816In[In]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195300_17816In-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195300_17816InFAWKES[FAWKES]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195300_17816-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195300_17816Out[Out]
    Phonebook.RyanW84TestResults-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195301_19208[Deploy_Ryanw 20250413T195301_19208]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195301_19208-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195301_19208In[In]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195301_19208In-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195301_19208InFAWKES[FAWKES]
    Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195301_19208-->Phonebook.RyanW84TestResultsDeploy_Ryanw_20250413T195301_19208Out[Out]
    Phonebook.RyanW84-->Phonebook.RyanW84Validators[Validators]
    Phonebook.RyanW84Validators-->Phonebook.RyanW84ValidatorsContactValidator.cs((ContactValidator.cs))
    Phonebook.RyanW84ValidatorsContactValidator.cs-->|class|Phonebook.RyanW84ValidatorsContactValidator.csContactValidator[ContactValidator]
    Phonebook.RyanW84ValidatorsContactValidator.csContactValidator-->|method|Phonebook.RyanW84ValidatorsContactValidator.csContactValidatorisPhoneNumberValid(isPhoneNumberValid)
    Phonebook.RyanW84ValidatorsContactValidator.csContactValidator-->|method|Phonebook.RyanW84ValidatorsContactValidator.csContactValidatorisEmailAddressValid(isEmailAddressValid)
    Phonebook.RyanW84-->Phonebook.RyanW84Program.cs((Program.cs))
